ycsb:
<<<<<<< HEAD
  image: docker.io/scylladb/ycsb:0.2.0
||||||| parent of 55e74319b (feature(ycsb): enable native YCSB loadbalancer)
  image: docker.io/scylladb/ycsb:1.0.0
=======
  image: docker.io/scylladb/ycsb:1.2.0
>>>>>>> 55e74319b (feature(ycsb): enable native YCSB loadbalancer)
