blank_issues_enabled: false  # Disables blank issue creation
contact_links:
  - name: " Press to open an issue in Jira."
    url: https://scylladb.atlassian.net/browse/SCT
    about: "Opening issues is not allowed in this Github repository."
