# TODO: Go over it and fix detauls
instance_provision: 'spot'
spot_max_price: 0.60
instance_provision_fallback_on_demand: true
azure_region_name:
  - eastus
user_credentials_path: '~/.ssh/scylla_test_id_ed25519'

azure_instance_type_db: 'Standard_L8s_v3'
azure_instance_type_loader: 'Standard_F4s_v2'
azure_instance_type_monitor: 'Standard_D2_v4'
# base on version 24.04 LTS documented here:
# https://documentation.ubuntu.com/azure/azure-how-to/instances/find-ubuntu-images/#free-long-term-support-offers
azure_image_loader: 'Canonical:ubuntu-24_04-lts:server:latest'
azure_image_monitor: 'Canonical:ubuntu-24_04-lts:server:latest'

availability_zone: ''
root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
root_disk_size_db: 30  # GB, increase root disk for larger swap (maximum: 16G)
azure_image_username: 'scyllaadm'
ami_loader_user: 'ubuntu'
ami_monitor_user: 'ubuntu'

ami_id_db_scylla: ''
ami_id_db_oracle: ''

use_preinstalled_scylla: true

backup_bucket_backend: 'azure'
backup_bucket_location: 'manager-backup-tests-us-east-1'

data_volume_disk_num: 0
data_volume_disk_type: 'gp2'
data_volume_disk_size: 500
data_volume_disk_iops: 10000 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
