instance_provision: 'on_demand'
gce_datacenter: 'us-east1-b'
gce_network: 'qa-vpc'

gke_cluster_version: '1.20'
gke_k8s_release_channel: ''

gce_instance_type_db: 'n1-standard-8'
gce_root_disk_type_db: 'pd-ssd'
gce_root_disk_size_db: 50
gce_n_local_ssd_disk_db: 3

n_db_nodes: 3

# '4.3.0' version doesn't work with GKE: https://github.com/scylladb/scylla/issues/8032
scylla_version: '4.5.3'
scylla_mgmt_agent_version: '2.6.0'
mgmt_docker_image: 'scylladb/scylla-manager:2.6.0'

# NOTE: If 'k8s_scylla_operator_docker_image' not set then the one from helm chart will be used.
# To test nightly builds define it like this: 'scylladb/scylla-operator:nightly'
k8s_scylla_operator_docker_image: ''
k8s_scylla_operator_helm_repo: 'https://storage.googleapis.com/scylla-operator-charts/latest'
k8s_scylla_operator_chart_version: 'latest'
k8s_cert_manager_version: '1.2.0'
k8s_deploy_monitoring: true

# NOTE: GKE requires 'k8s_scylla_utils_docker_image' be defined to enterprise Scylla version 2021+
#       to have more performant configuration of disks.
k8s_scylla_utils_docker_image: 'scylladb/scylla-enterprise:2021.1.6'

k8s_scylla_datacenter: 'us-east1-b'
k8s_scylla_rack: 'us-east1'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_disk_gi: 500
k8s_scylla_disk_class: 'local-raid-disks'

k8s_minio_storage_size: '60Gi'
k8s_loader_cluster_name: 'sct-loaders'
gce_instance_type_loader: 'e2-standard-4'

n_loaders: 1

gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: true

append_scylla_args: ''
docker_image: ''
backup_bucket_backend: 's3'
backup_bucket_location: 'minio-bucket'
