instance_provision: 'on_demand'
gce_datacenter: 'us-east1'
gce_network: 'qa-vpc'
gce_image_username: 'scylla-test'

gce_image_minikube: 'https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
gce_instance_type_minikube: 'n1-highmem-8'
gce_root_disk_type_minikube: 'pd-ssd'
gce_root_disk_size_minikube: 120
minikube_version: '1.11.0'

n_db_nodes: 3

k8s_scylla_operator_docker_image: 'scylladb/scylla-operator:v0.1.9'
scylla_version: '4.0.0'
scylla_mgmt_agent_version: '2.0.2'
k8s_scylla_datacenter: 'gce'
k8s_scylla_rack: 'minikube'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_cpu_n: 1
k8s_scylla_mem_gi: 2
k8s_scylla_disk_gi: 5

gce_image: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_instance_type_loader: 'e2-standard-2'
gce_root_disk_type_loader: 'pd-standard'
gce_n_local_ssd_disk_loader: 0

n_loaders: 1

gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: false
