instance_provision: 'on_demand'
gce_datacenter: 'us-east1'
availability_zone: 'c'
gce_network: 'qa-vpc'
gce_image_username: 'scylla-test'

gke_cluster_version: '1.27'
gke_k8s_release_channel: ''

gce_instance_type_db: 'n1-standard-8'
gce_root_disk_type_db: 'pd-ssd'
root_disk_size_db: 50
gce_n_local_ssd_disk_db: 3

n_db_nodes: 4
k8s_n_scylla_pods_per_cluster: 3
k8s_n_monitor_nodes: 0
k8s_n_auxiliary_nodes: 2

k8s_instance_type_auxiliary: 'n1-standard-2'

scylla_version: '5.2.11'

# NOTE: If 'k8s_scylla_operator_docker_image' not set then the one from helm chart will be used.
# To test nightly builds define it like this: 'scylladb/scylla-operator:nightly'
k8s_scylla_operator_docker_image: ''
k8s_scylla_operator_helm_repo: 'https://storage.googleapis.com/scylla-operator-charts/latest'
k8s_scylla_operator_chart_version: 'latest'
k8s_cert_manager_version: '1.8.0'
k8s_deploy_monitoring: false
k8s_enable_performance_tuning: true

# NOTE: GKE requires 'k8s_scylla_utils_docker_image' be defined to enterprise Scylla version 2021+
#       to have more performant configuration of disks.
k8s_scylla_utils_docker_image: 'scylladb/scylla-enterprise:2021.1.6'

k8s_use_chaos_mesh: true
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_disk_gi: 1100
# NOTE: use any of the following pairs:
#   'k8s_scylla_disk_class=local-raid-disks'   and 'k8s_local_volume_provisioner_type=static'
#   'k8s_scylla_disk_class=scylladb-local-xfs' and 'k8s_local_volume_provisioner_type=dynamic'
k8s_scylla_disk_class: 'scylladb-local-xfs'
k8s_local_volume_provisioner_type: 'dynamic'

k8s_minio_storage_size: '60Gi'
k8s_loader_cluster_name: 'sct-loaders'
gce_instance_type_loader: 'e2-standard-4'

# NOTE: if we do not specify 'k8s_n_loader_pods_per_cluster' then value of the 'n_loaders' is used
n_loaders: 1

gce_image_monitor: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: true

# TODO: add '--abort-on-seastar-bad-alloc' arg to the 'append_scylla_args' option when
#       following operator bug gets fixed: https://github.com/scylladb/scylla-operator/issues/991
#       '--blocked-reactor-notify-ms 100' cannot be set, because it gets set by operator itself
append_scylla_args: '--abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1'
docker_image: ''
backup_bucket_backend: 's3'
backup_bucket_location: 'minio-bucket'

# NOTE: Define a separate image for the 'cassandra stress' that supports 'serverless' feature.
#       It will allow to test 'serverless' feature against any stable Scylla release
#       with old 'cassandra-stress' binary.
stress_image:
  cassandra-stress: 'scylladb/scylla:5.2.11'
