# In order to have EKS Cluster created you need to provide subnets from two different availability zone
# otherwise it will fail due to the validation.
# At the same time Scylla Operator can't work properly when nodes within one rack are deployed into
#  different availability zones.
# To make it work when node groups are created we pick subnets only from first availability zone
# As result you need to specify two AZ to make it work, but scylla will occupy resources only from first one

availability_zone: 'a,b'
instance_provision: 'on_demand'
instance_type_db: 'i4i.4xlarge'

eks_cluster_version: '1.32'
eks_role_arn: 'arn:aws:iam::797456418907:role/eksServicePolicy'
eks_service_ipv4_cidr: '172.20.0.0/16'
eks_nodegroup_role_arn: 'arn:aws:iam::797456418907:role/helm-test-worker-nodes-NodeInstanceRole-6ACHDYEKNN3I'
# NOTE: https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
eks_vpc_cni_version: 'v1.19.2-eksbuild.5'

scylla_version: '6.2.3'
k8s_cert_manager_version: '1.19.1'

k8s_deploy_monitoring: false
k8s_enable_performance_tuning: true

k8s_loader_cluster_name: 'sct-loaders'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_disk_gi: 3490
# NOTE: use any of the following pairs:
#   'k8s_scylla_disk_class=local-raid-disks'   and 'k8s_local_volume_provisioner_type=static'
#   'k8s_scylla_disk_class=scylladb-local-xfs' and 'k8s_local_volume_provisioner_type=dynamic'
k8s_scylla_disk_class: 'scylladb-local-xfs'
k8s_local_volume_provisioner_type: 'dynamic'

# NOTE: If 'k8s_scylla_operator_docker_image' not set then the one from helm chart will be used.
# To test nightly builds define it like this: 'scylladb/scylla-operator:nightly'
k8s_scylla_operator_docker_image: ''
k8s_scylla_operator_helm_repo: 'https://storage.googleapis.com/scylla-operator-charts/latest'
k8s_scylla_operator_chart_version: 'latest'
k8s_use_chaos_mesh: true

k8s_minio_storage_size: '60Gi'

k8s_n_monitor_nodes: 0
# NOTE: if we do not specify 'k8s_n_loader_pods_per_cluster' then value of the 'n_loaders' is used
n_loaders: 1
n_db_nodes: 4
k8s_n_scylla_pods_per_cluster: 3
k8s_n_auxiliary_nodes: 3

k8s_instance_type_auxiliary: 't3.large'

# TODO: add '--abort-on-seastar-bad-alloc' arg to the 'append_scylla_args' option when
#       following operator bug gets fixed: https://github.com/scylladb/scylla-operator/issues/991
#       '--blocked-reactor-notify-ms 100' cannot be set, because it gets set by operator itself
append_scylla_args: '--abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1'
docker_image: ''
