name: Cache issues status
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  collect_n_upload:
    runs-on: ubuntu-latest
    # run only on main repository, won't work on forks
    if: github.repository == 'scylladb/scylla-cluster-tests'
    steps:
      - run: |
          mkdir -p issues
          mkdir -p issues/pull-requests
          for repo in scylladb scylla-enterprise scylla-manager scylla-operator scylla-cluster-tests scylla-dtest qa-tasks scylla-tools-java siren ; do
            gh issue list --state all --json number,state,labels,title --limit 30000 --template '{{range .}}{{.number}},{{.state}},{{range .labels}}{{.name}}|{{end}},{{.title}}{{println ""}}{{end}}' --repo scylladb/$repo > issues/scylladb_$repo.csv
            gh pr list --state all --json number,state,labels,title --limit 30000 --template '{{range .}}{{.number}},{{.state}},{{range .labels}}{{.name}}|{{end}},{{.title}}{{println ""}}{{end}}' --repo scylladb/$repo > issues/pull-requests/scylladb_$repo.csv
          done
        env:
          GH_TOKEN: ${{ secrets.ISSUE_ASSIGNMENT_TO_PROJECT_TOKEN }}
      - name: Upload folder to bucket
        uses: a-sync/s3-uploader@2.0.1
        with:
          args: --recursive --grants full=id=${{ secrets.CLOUDIUS_SYSTEMS_CANONICAL_ID }} read=id=${{ secrets.DBAAS_DATA_QA_CANONICAL_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: 'issues'
          FILE: ./issues
